# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore backend-app
    - name: Build
      run: |
        dotnet build backend-app --no-restore -c release
        dotnet publish backend-app /p:Configuration=Release /p:PublishProfile=FolderProfile -o /site
    - name: Test
      run: dotnet test backend-app --no-build --verbosity normal
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        uses: TheDoctor0/zip-release@0.6.2
        with:
          # Filename for archive
          #filename: # default is release.zip
          # Base path for archive files
          #path: # optional, default is .
          # Working directory before zipping
          directory: site # optional, default is .
          # List of excluded files / directories
          # exclusions: # optional, default is 
          # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
          # recursive_exclusions: # optional, default is 
          # Tool to use for archiving
          # type: # optional, default is zip
