# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore webapp
    - name: Build
      run: |
        dotnet build webapp --no-restore -c release
        dotnet publish webapp /p:Configuration=Release /p:PublishProfile=FolderProfile -o site
    - name: Test
      run: dotnet test webapp --no-build --verbosity normal
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        directory: site
    - name: list
      run: ls .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: release.zip
